---
# Adapted from https://blog.travis-ci.com/2017-11-30-testing-ansible-roles-using-docker-on-travis

language: generic
sudo: required

env:
  - distribution: ubuntu
    version: bionic
    ros2_distro: bouncy
  - distribution: ubuntu
    version: bionic
    ros2_distro: crystal
  - distribution: ubuntu
    version: bionic
    ros2_distro: dashing
  - distribution: ubuntu
    version: bionic
    ros2_distro: eloquent
  - distribution: ubuntu
    version: focal
    ros2_distro: foxy

jobs:
  allow_failures: # https://github.com/ansible/ansible/issues/68645
    - env: 
      - distribution: ubuntu
        version: focal
        ros2_distro: foxy

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/ansible-role-ros2:ro ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -vvvv /etc/ansible/roles/ansible-role-ros2/tests/test-${ros2_distro}.yml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -vvvv /etc/ansible/roles/ansible-role-ros2/tests/test-${ros2_distro}.yml'
  - >
    sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-ros2/tests/test-${ros2_distro}.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - 'sudo docker exec "$(cat ${container_id})" bin/bash -c "[ -f /opt/ros/${ros2_distro}/setup.bash ] && (echo setup.bash exists under /opt/ros/${ros2_distro}/ && exit 0) || (echo setup.bash not found under /opt/ros/${ros2_distro}/ && exit 1)"'
  - 'sudo docker exec "$(cat ${container_id})" bin/bash -c "[ -f /home/${distribution}/dev_ws/install/setup.bash ] && (echo setup.bash exists under /home/${distribution}/dev_ws/install/ && exit 0) || (echo setup.bash not found under /home/${distribution}/dev_ws/install/ && exit 1)"'
  - 'sudo docker rm -f "$(cat ${container_id})"'


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
